### PR TITLE
Update Ruby version in GitHub Actions workflow to 3.4

### PR DESCRIPTION
**Pull request by ydah**
Ruby 3.4 has been released🎉
https://www.ruby-lang.org/en/news/2024/12/25/ruby-3-4-0-released/

______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [ ] Added tests.
- [x] Updated documentation.
- [ ] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

If you have created a new cop:

- [ ] Added the new cop to `config/default.yml`.
- [ ] The cop is configured as `Enabled: pending` in `config/default.yml`.
- [ ] The cop documents examples of good and bad code.
- [ ] The tests assert both that bad code is reported and that good code is not reported.
- [ ] Set `VersionAdded: "<<next>>"` in `default/config.yml`.

If you have modified an existing cop's configuration options:

- [ ] Set `VersionChanged: "<<next>>"` in `config/default.yml`.

### CODE REVIEW

**Review by pirj — APPROVED** [review]
Thank you!

**Comment by pirj** [comment]
How do you guys feel about dropping everything ([EOL](https://endoflife.date/ruby)) below Ruby 3.1, @rubocop/rubocop-rspec ?

**Comment by ydah** [comment]
FYI: RuboCop has changed its maintenance policy and decided to support Ruby 2.7 for an extended period, regardless of Ruby 3.0's EOL. For more details, please see the following:
https://docs.rubocop.org/rubocop/1.60/compatibility.html#support-matrix

**Comment by pirj** [comment]
The comment grew big and I published it as a discussion instead https://github.com/rubocop/rubocop-rspec/discussions/2018

**Comment by bquorning** [comment]
Just FYI, CI is still installing Ruby v3.4.0-rc1, presumably until https://github.com/ruby/setup-ruby/pull/677 is merged.

**Pull request merged**
